nmo api vendor
edgelesssys/constellation pull request #1172
Opened 2023-02-13 07:34 UTC by malt3

### Proposed change(s)

- Vendor node-maintenance-operator api folder

### Additional info
- Removes some unneeded dependencies and unblocks #766

### Checklist

- [x] Add labels (e.g., for changelog category)

2023-02-13 07:52 UTC, malt3 commented
@thomasten can you look at the vendored code license? Also: Ideas on how we can handle the license check? (Maybe we can ignore the 3rdparty folder?)
 https://github.com/edgelesssys/constellation/commit/80785fce9ab8788f06cbfa3373d443d29aeac067

2023-02-13 08:43 UTC, thomasten commented
I believe doing it like this is sufficient to comply with the license. At least if you haven't modified any of the copied files.
Ignoring the 3rdparty folder in the license header check seems the right solution to me.

2023-02-14 16:54 UTC, katexochen requested changes

2023-02-14 16:54 UTC, katexochen commented on 3rdparty/node-maintenance-operator/api/v1beta1/download.sh
> +EXPECTED_SHA256=$3
nit: use lower case variables for unexported values.

2023-02-14 16:54 UTC, katexochen commented on 3rdparty/node-maintenance-operator/go.mod
> +module github.com/edgelesssys/constellation/v2/operators/constellation-node-operator/v2/3rdparty/node-maintenance-operator
```suggestion
module github.com/edgelesssys/constellation/v2/3rdparty/node-maintenance-operator
```
I would use the real path for the module name, everything else is confusing.

2023-02-14 17:45 UTC, katexochen approved these changes
lgtm :hatched_chick:

2023-02-14 17:46 UTC, merged