bootstrapper: make Azure auth method configurable on cluster init
edgelesssys/constellation pull request #1346
Opened 2023-03-06 13:47 UTC by malt3

[AB#2963](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/2963). This is the second step of [AB#2961](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/2961)
### Proposed change(s)

- bootstrapper: make Azure auth method configurable on cluster init
- helm: use `azure.json` secret for all deployments (including cluster-autoscaler)
- cli: send `preferredAuthMethod` for Azure in-cluster auth to allow for client side configuration in the future

### Checklist

- [x] Add labels (e.g., for changelog category)
- [x] Link to Milestone

2023-03-13 23:11 UTC, 3u13r requested changes

2023-03-14 09:38 UTC, derpsteb reviewed
[Smoke test](https://github.com/edgelesssys/constellation/actions/runs/4414262630) :green_circle: 

Code LGTM.

2023-03-14 10:41 UTC, derpsteb approved these changes

2023-03-22 18:16 UTC, 3u13r requested changes

2023-03-22 18:16 UTC, 3u13r commented on internal/cloud/azure/azure.go
> +	UserAssignedIdentityID      string `json:"userAssignedIdentityID,omitempty"`
As discussed, we should use the UAMI that the user defined in the `constellation-config.yaml` and _not_ autoselect it. This is not 100% straight forward, as we need to translate the resource URI string of the UAMI from the config to its "Client ID". (see: https://cloud-provider-azure.sigs.k8s.io/install/configs/).

2023-04-03 11:49 UTC, 3u13r requested changes

2023-04-03 11:49 UTC, 3u13r commented on cli/internal/cmd/init.go
> +			PreferredAuthMethod: azureshared.AuthMethodUserAssignedIdentity,
We should switch this back. I've changed this in my PR for testing purposes.

2023-04-03 13:01 UTC, merged