ci: upload cli version list
edgelesssys/constellation pull request #1377
Opened 2023-03-08 13:09 UTC by msanft

### Proposed change(s)

- Upload a version list of CLI versions to the versionsapi as a CI action
- [Successful run](https://github.com/edgelesssys/constellation/actions/runs/4363889664/jobs/7631996913)

### Checklist

- [x] Add labels (e.g., for changelog category)
- [x] Link to Milestone

2023-03-08 15:17 UTC, katexochen requested changes

2023-03-08 15:17 UTC, katexochen commented on internal/versionsapi/cli/add.go
> +	}
Use `versionsapi.VersionKindFromString()` instead.

2023-03-08 15:17 UTC, katexochen commented on internal/versionsapi/list.go
> +	if l.Kind != VersionKindImage && l.Kind != VersionKindCLI {
Maybe switch to `l.Kind == VersionKindUnknown`?

2023-03-08 15:17 UTC, katexochen commented on .github/workflows/on-release.yml
>              "${latest_flag}"
Could you try to replace this with the according workflow call? Can't remember why it isn't used her, and @malt3 can't either. It is currently unsynchronized, so things could easily go wrong.

2023-03-09 11:07 UTC, msanft commented
[Successful run after changes](https://github.com/edgelesssys/constellation/actions/runs/4373371728/jobs/7652321337)

2023-03-09 15:39 UTC, malt3 commented
Just a heads-up: This branch should be rebased before merge and bazel build files should be generated.
[This document](https://github.com/edgelesssys/constellation/blob/main/dev-docs/workflows/build-test-run.md) has up-to-date information on the required tasks (`bazel run gazelle`).

2023-03-10 09:21 UTC, katexochen approved these changes
lgtm

2023-03-10 09:21 UTC, merged