ci: sort apk hashes
edgelesssys/constellation pull request #1560
Opened 2023-03-30 13:46 UTC by katexochen

### Proposed change(s)

- Makes better diffs

### Checklist

- [x] Add labels (e.g., for changelog category)

2023-03-30 15:45 UTC, 3u13r requested changes

2023-03-30 17:08 UTC, 3u13r commented on hack/package-hasher/Containerfile.apk.hasher
> +RUN sort -k2 -o SHA256SUMS SHA256SUMS
I'd suggest to also sort the current file, so that we can already enjoy the sorting for the next change.

2023-03-31 07:31 UTC, malt3 approved these changes
LGTM when @3u13r comment is resolved

2023-03-31 16:12 UTC, 3u13r approved these changes
LGTM

2023-03-31 16:12 UTC, merged