ci: idempotent image upload
edgelesssys/constellation pull request #1699
Opened 2023-04-27 12:51 UTC by malt3

### Proposed change(s)

- implement idempotent upload of os images
- use native go code for os image upload
- remove legacy bash scripts for uploads

2023-04-27 15:00 UTC, 3u13r requested changes

2023-04-27 15:07 UTC, malt3 commented on image/upload/upload.go
> +	rootCmd.Flags().String("csp", "", "Cloud service provider that this upload targets.")
Yeah the amount of flags got a little bit our of hand. I'll move each CSP to a subcommand with their own flags.

2023-04-27 15:13 UTC, 3u13r commented on image/upload/upload.go
Ah I see, so the main idea is to keep the creation and deletion of resources together to keep them in sync. Makes sense.

2023-05-02 16:29 UTC, 3u13r requested changes

2023-05-02 16:29 UTC, 3u13r commented on internal/osimage/gcp/gcpupload.go
> +	// }).String()
This is unused and can be removed I assume?

2023-05-02 16:37 UTC, malt3 commented on .github/workflows/build-os-image.yml
> +      QEMU_JSON_OUTPUT: mkosi.output.qemu/fedora~37/image-upload.json
I don't think it's worth it. We would need to let bash resolve the wildcard (without quotes). 
Right now we can simply search/replace for `fedora~37`.

2023-05-03 12:31 UTC, 3u13r commented on .github/workflows/build-os-image.yml
> +      QEMU_JSON_OUTPUT: mkosi.output.qemu/fedora~37/image-upload.json
I have no strong opinion about your suggestion. If you think it's an improvement then please go ahead.

2023-05-03 16:52 UTC, 3u13r approved these changes
LGTM

2023-05-05 10:06 UTC, merged