ci: update the e2e-upgrade fromVersion
edgelesssys/constellation pull request #1772
Opened 2023-05-16 08:45 UTC by derpsteb

### Proposed change(s)

- During weekly tests we always want to test upgrades from the latests release version to current main. The `fromVersion` has fallen behind and is updated. Also add a release step to have this updated automatically during release. The idea is that the bigger version of the two versions (existing fromVersion & release version) is kept in fromVersion.

2023-05-16 12:54 UTC, katexochen requested changes

2023-05-16 12:54 UTC, katexochen commented on .github/workflows/release.yml
> +          newVersion=$(printf '%s\n${{ inputs.version }}' "$fromVersion" | sort -V | tail -n 1)
Add comment why

2023-05-16 12:54 UTC, katexochen commented on .github/workflows/release.yml
> +          sed -i "s/fromVersion: \[\".*\"\]/fromVersion: \[\"$newVersion\"\]/g" .github/workflows/e2e-test-release.yml
Write first sed regex to var and grep frist.

2023-05-17 08:22 UTC, 3u13r requested changes
We should probably also update `.github/workflows/e2e-test-weekly.yml:256`  and then attach a test run in the PR.

2023-05-17 09:52 UTC, derpsteb commented
[Azure 1+1, full upgrade](https://github.com/edgelesssys/constellation/actions/runs/5001813500)

2023-05-19 08:19 UTC, 3u13r approved these changes
LGTM

2023-05-22 07:16 UTC, derpsteb commented
Superseeded by: https://github.com/edgelesssys/constellation/pull/1758

2023-05-22 07:16 UTC, closed without merging