Constellation create with Terraform (GCP)
edgelesssys/constellation pull request #197
Opened 2022-09-27 09:16 UTC by katexochen

### Proposed change(s)

- `constellation create` now used Terraform internally to create and destroy the needed resources
- Metadata like uid and role are now taken from the metadata API instead of parsing them from the instance name

### Checklist

- [ ] Update [CHANGELOG.md](https://github.com/edgelesssys/constellation/blob/main/CHANGELOG.md)
- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Add documentation to the Terraform module, especially regarding the required values, for people that want to write their own
- [x] Link to Milestone

### Future ToDos (not this PR)

- [ ]  Write `.tfvars` file with [hashicorp/hcl ](https://github.com/hashicorp/hcl)
- [ ] Maybe generate Go structs for variables from `variables.tf` file

2022-09-27 16:02 UTC, Nirusu reviewed
I'll test this again more in-depth when it's ready for review. Some nits.

2022-09-29 16:27 UTC, katexochen commented
Image to test: `projects/constellation-331613/global/images/debug-tf-gcp-paul`

2022-09-30 09:14 UTC, Nirusu requested changes

2022-09-30 09:14 UTC, Nirusu commented on cli/internal/cloudcmd/create.go
> +			return terraform.New(ctx, cloudprovider.GCP)
This breaks QEMU and other CSPs. The cloud provider should be passed as a variable to the function.

2022-09-30 09:22 UTC, Nirusu commented on CHANGELOG.md
> +- The `constellation create` on GCP now uses Terraform to create and destroy cloud resources.
You can also add the GCP no public IP change here (and that SSH now needs to be manually allowed before it can be used).

2022-09-30 14:02 UTC, daniel-weisse approved these changes
Works on my cloud subscription :+1:

2022-09-30 14:50 UTC, Nirusu approved these changes
Approved under duress ;) 
Just kidding, looks good to me.

2022-09-30 14:50 UTC, merged