bootstrapper: remove unused CloudServiceAccountUri from init request
edgelesssys/constellation pull request #2182
Opened 2023-08-08 13:52 UTC by elchead

### Context

Due to the helm chart movement, the parameter is no longer needed.

### Proposed change(s)

-

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [x] Add labels (e.g., for changelog category)
- [ ] Is PR title adequate for changelog?
- [x] Link to Milestone

2023-08-08 13:53 UTC, elchead commented
running E2E: https://github.com/edgelesssys/constellation/actions/runs/5797850611

2023-08-09 08:55 UTC, elchead commented
will need new nightly images to ensure E2E keeps working

2023-08-09 09:55 UTC, 3u13r requested changes

2023-08-09 09:55 UTC, 3u13r commented on bootstrapper/initproto/init.proto
> -  string cloud_service_account_uri = 4;
Until we decide that we want to completely remove the lines of removed entries, I'd prefer:
```
// string cloud_service_account_uri = 4; removed
```

2023-08-09 10:37 UTC, 3u13r requested changes

2023-08-09 10:37 UTC, 3u13r commented on bootstrapper/initproto/init.proto
> +  // string cloud_service_account_uri = 4; removed
I don't think we should keep this line it if we proceed as stated in their docs, but remove it entirely.

2023-08-09 11:57 UTC, 3u13r approved these changes
LGTM

2023-08-09 12:16 UTC, merged