cli: new flag to skip phases of upgrade
edgelesssys/constellation pull request #2310
Opened 2023-09-06 08:26 UTC by elchead

### Context

Currently it is not possible to select / deselect specific upgrades (terraform, helm, k8s, node image).

### Proposed change(s)

- add a new `--skip-phases` flag that accepts a list of phases to skip during the upgrade

### Related issue
- AB#3407

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Add labels (e.g., for changelog category)
- [ ] Is PR title adequate for changelog?
- [ ] Link to Milestone

2023-09-06 11:39 UTC, daniel-weisse commented on cli/internal/cmd/upgradeapply.go
> +		if p == phase {
```suggestion
		if strings.EqualFold(p, phase) {
```
Use [`strings.EqualFold`](https://pkg.go.dev/strings#EqualFold) to have a reliable way for comparing case-insensitive strings.

2023-09-06 13:09 UTC, daniel-weisse approved these changes
Can you add a ticket to document this feature?

2023-09-06 13:09 UTC, daniel-weisse commented on cli/internal/cmd/upgradeapply.go
> +func (s skipPhases) Contains(phase skipPhase) bool {
```suggestion
// contains returns true if the list of phases contains the given phase.
func (s skipPhases) contains(phase skipPhase) bool {
```

2023-09-07 06:54 UTC, malt3 approved these changes

2023-09-08 09:42 UTC, thomasten requested changes

2023-09-08 09:42 UTC, thomasten commented on cli/internal/cmd/upgradeapply.go
> +	skipK8sPhase skipPhase = "k8s"
this is not implemented

2023-09-08 09:42 UTC, thomasten commented on cli/internal/cmd/upgradeapply.go
> +	cmd.Flags().StringSlice("skip-phases", []string{}, "skip one or multiple phases of the upgrade process {infrastructure|helm|node|k8s}\n")
```suggestion
	cmd.Flags().StringSlice("skip-phases", nil, "comma-separated list of upgrade phases to skip\n"+
		"one or multiple of { infrastructure | helm | node | k8s }")
```
optional: I'd make it a bit more clear how to pass these values

2023-09-08 09:42 UTC, thomasten commented on cli/internal/cmd/upgradeapply.go
> +	skipPhases := []skipPhase{}
```suggestion
	var skipPhases []skipPhase
```
nit: [nil is a valid slice](https://github.com/edgelesssys/wiki/blob/master/company/gostyle.md#nil-is-a-valid-slice)

2023-09-08 12:25 UTC, thomasten approved these changes
Code LGTM. (I haven't tried it out.)

2023-09-08 12:26 UTC, daniel-weisse approved these changes

2023-09-08 12:55 UTC, merged