cli: new flag for JSON output of `constellation verify`
edgelesssys/constellation pull request #2391
Opened 2023-09-28 14:20 UTC by elchead

### Context

Motivated by https://github.com/edgelesssys/constellation/pull/2357, this PR provides a JSON output format as communication interface between the CLI and the attestationconfigapi upload tool through a new flag `constellation verify--json`.

### Proposed change(s)

- new internal pkg `verify` to provide the types for JSON serialization. 
- new `--json` flag

### Related issue
- AB#3462

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Add labels (e.g., for changelog category)
- [ ] Is PR title adequate for changelog?
- [ ] Link to Milestone

2023-09-28 16:52 UTC, 3u13r commented
This is not the implementation I suggested.
> implement a custom mashaller and unmarshaller which recursively parses the attestationDoc to a struct containing the parsed InstanceInfo

I said that we should implement a custom mashaller and unmarsaller. As we already do in e.g. https://github.com/edgelesssys/constellation/blob/cli/verify/json-output/internal/attestation/idkeydigest/idkeydigest.go#L180

Did you encounter any issue with this approach, or why did you prefer your implementation?

2023-09-29 06:41 UTC, daniel-weisse commented
> To only obtain the JSON output needed for the upload tool, some lines need to be omitted

This seems like bad UX. If a command offers me the option to receive JSON output, I would expected all output to be JSON, not just some of it.
What about omitting the hints about retrieval of information from the id/state file, and potentially adding the verification status to the JSON output?
E.g.
```bash
$ constellation verify
{
  "attestationDocument": {
    // ...
  },
  "verification": "ok",
}
```

2023-09-29 06:49 UTC, thomasten commented
> If a command offers me the option to receive JSON output, I would expected all output to be JSON, not just some of it.

A common way tools solve this is printing the JSON output to stdout and everything else to stderr.

2023-09-29 07:50 UTC, elchead commented
> This is not the implementation I suggested.
> 
> > implement a custom mashaller and unmarshaller which recursively parses the attestationDoc to a struct containing the parsed InstanceInfo
> 
> I said that we should implement a custom mashaller and unmarsaller. As we already do in e.g. https://github.com/edgelesssys/constellation/blob/cli/verify/json-output/internal/attestation/idkeydigest/idkeydigest.go#L180
> 
> Did you encounter any issue with this approach, or why did you prefer your implementation?

I think if we wan

> > To only obtain the JSON output needed for the upload tool, some lines need to be omitted
> 
> This seems like bad UX. If a command offers me the option to receive JSON output, I would expected all output to be JSON, not just some of it. What about omitting the hints about retrieval of information from the id/state file, and potentially adding the verification status to the JSON output? E.g.
> 
> ```shell
> $ constellation verify
> {
>   "attestationDocument": {
>     // ...
>   },
>   "verification": "ok",
> }
> ```

I print to stderr now. Do we need the verification ok in the json output too? Since we don't foresee consuming this json in any other way besides the upload tool at the moment, I would drop it. An error of `verify` should indicate that the verification was not ok right?

2023-09-29 07:55 UTC, elchead commented
> This is not the implementation I suggested.
> 
> > implement a custom mashaller and unmarshaller which recursively parses the attestationDoc to a struct containing the parsed InstanceInfo
> 
> I said that we should implement a custom mashaller and unmarsaller. As we already do in e.g. https://github.com/edgelesssys/constellation/blob/cli/verify/json-output/internal/attestation/idkeydigest/idkeydigest.go#L180
> 
> Did you encounter any issue with this approach, or why did you prefer your implementation?

I think it's better to use a proper type, because to unmarshal and read the struct we would need this anyways (as required by the upload tool)

2023-10-05 08:00 UTC, derpsteb commented
Recap of our conversation on the phone:
- Ideally we could use a type from go-sev-guest that recursively parses all fields in an SNP report. However, looking at how scattered the bits of parsing logic currently are, it seems like considerably more effort to change the type upstream. It is also questionable if the maintainers would even want such a change.
- I personally don't think it is urgent to upstream this. It would be easy to adapt this PR to an upstream implementation, if one would be released/implemented tomorrow. 
- Using `newSNPReport` in the existing formatter would make sense to reduce code duplication.
- A point in the future when we _should_ try upstreaming this imo: when we plan on using the Report type in more places than attestationconfigapi and verify. 
- I opened an issue to see how the upstream maintainers feel about such a contribution. The answer can help inform our decision here: https://github.com/google/go-sev-guest/issues/91

2023-10-05 14:21 UTC, elchead commented on cli/internal/cmd/verify.go
> +	// TODO(elchead): omit quotes?
> Is this a question for the reviewer or for yourself? Is this something we can decide and "fix" now?

I believe that we don't need the quote output in the json format and just wanted to confirm.

2023-10-05 14:22 UTC, elchead commented on cli/internal/cmd/verify.go
> +	// TODO(elchead): unify the formatters to share the parsing logic
Most of the logic is now shared already through the parse SNP report. I remove this TODO.

2023-10-05 16:05 UTC, 3u13r submitted a review, later dismissed
LGMT, I'd suggest to get a second approval for this though.

2023-10-06 09:37 UTC, elchead commented
good catch, thanks! Since we also only support this for Azure on the default printer, I return an unsupported message:
```
./constellation verify -o json
Using endpoint from "constellation-id.json". Specify --node-endpoint to override this.
Using ID from "constellation-id.json". Specify --cluster-id to override this.
Error: printing attestation document: JSON output is currently only supported for Azure
```

2023-10-06 12:27 UTC, derpsteb commented on cli/internal/cmd/verify.go
> +	c.log.Debugf("Flag 'raw' set to %t", force)
```suggestion
	c.log.Debugf("Flag 'output' set to %t", output)
```

and move to after the error check.

2023-10-06 12:29 UTC, derpsteb approved these changes
LGTM :+1:

2023-10-06 14:06 UTC, 3u13r requested changes

2023-10-07 09:21 UTC, 3u13r approved these changes
LGTM

2023-10-07 14:24 UTC, merged