docs: refer to apply command instead of `init` or `upgrade apply`
edgelesssys/constellation pull request #2487
Opened 2023-10-20 10:47 UTC by daniel-weisse

### Context
Docs should not use deprecated commands

### Proposed change(s)

- refer to apply command instead of `init` or `upgrade apply`

### Additional info

- AB#3499
- The asciinema should be updated at some point to also make use of `apply` instead of `init`

### Checklist

- [x] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [x] Add labels (e.g., for changelog category)
- [x] Is PR title adequate for changelog?
- [x] Link to Milestone

2023-10-20 12:29 UTC, 3u13r approved these changes
LGTM

2023-10-20 13:24 UTC, malt3 approved these changes

2023-10-20 13:34 UTC, thomasten requested changes
there are two more `init`s in `workflows/terminate.md` and `architecture/orchestration.md`

2023-10-20 13:49 UTC, elchead commented
lgtm besides thomas comment.

2023-10-23 11:43 UTC, thomasten approved these changes

2023-10-27 06:31 UTC, merged