terraform-provider: require kubernetes and microservice version
edgelesssys/constellation pull request #2791
Opened 2024-01-03 14:31 UTC by elchead

### Context

### Proposed change(s)

-

### Additional info

- AB#1234
- Any additional information or context

### Checklist

- [ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Add labels (e.g., for changelog category)
- [ ] Is PR title adequate for changelog?
- [ ] Link to Milestone

2024-01-03 14:45 UTC, msanft submitted a review, later dismissed

2024-01-03 14:45 UTC, msanft commented on terraform-provider-constellation/examples/full/aws_cluster.tf
Same for the examples. Don't we need the microservice version here?

2024-01-04 09:43 UTC, elchead commented
Running [E2E](https://github.com/edgelesssys/constellation/actions/runs/7407878253/job/20154938654)

2024-01-04 10:18 UTC, msanft requested changes
LGTM except for the one comment

2024-01-04 10:20 UTC, elchead commented on terraform-provider-constellation/examples/full/aws/main.tf
> +  microservice_version = "vX.Y.Z"
no. version refers to the image_version is and is renamed to make this more clear in #2775

2024-01-04 14:31 UTC, msanft approved these changes

2024-01-04 15:25 UTC, merged