helm: update AWS CSI driver
edgelesssys/constellation pull request #3121
Opened 2024-05-24 06:28 UTC by msanft

### Context

Our fork of the AWS CSI driver got rebased to a new upstream version, we also need to update the vendored chart in this repository.

### Proposed change(s)

- Pull in the new chart from our fork.

### Additional info

- AB#4074

### Checklist

- [x] Run the E2E tests that are relevant to this PR's changes
  - [AWS Perf-Bench, which uses CSI](https://github.com/edgelesssys/constellation/actions/runs/9207975427)
- [x] Add labels (e.g., for changelog category)
- [x] Is PR title adequate for changelog?
- [x] Link to Milestone

2024-05-24 06:35 UTC, daniel-weisse requested changes
To update the chart, you should update the version in the [update script](https://github.com/edgelesssys/constellation/blob/main/internal/constellation/helm/update-csi-charts.sh#L71) and run `bazel run //:generate`

2024-05-24 06:35 UTC, daniel-weisse commented on internal/constellation/helm/charts/edgeless/csi/charts/aws-csi-driver/values.yaml
Can you pin the images here by hash again?
Also, the actual CSI driver image is still at `v1.1.0`, I don't think that is correct when updating the chart to `v1.2.0`

2024-05-24 06:52 UTC, msanft commented on internal/constellation/helm/charts/edgeless/csi/charts/aws-csi-driver/values.yaml
Thanks for the heads-up. Will re-run the CI

2024-05-27 13:22 UTC, daniel-weisse approved these changes

2024-05-27 14:22 UTC, merged