devdocs: pr title conventions
edgelesssys/constellation pull request #890
Opened 2023-01-06 12:35 UTC by katexochen

Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>

### Proposed change(s)

- Feel free to discuss

### Checklist

- [x] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)
- [ ] Add labels (e.g., for changelog category)

2023-01-06 13:44 UTC, malt3 approved these changes

2023-01-06 13:52 UTC, daniel-weisse approved these changes

2023-01-06 14:58 UTC, leongross requested changes

2023-01-06 14:58 UTC, leongross commented on .github/docs/conventions.md
> +In case the scope of your PR is to wide, use the alternative format.
```suggestion
In case the scope of your PR is too wide, use the alternative format.
```

2023-01-06 15:26 UTC, leongross approved these changes
lgtm

2023-01-06 15:56 UTC, thomasten approved these changes
❤️

2023-01-06 16:18 UTC, stdoutput approved these changes
👍

2023-01-06 16:55 UTC, Nirusu approved these changes

2023-01-06 16:55 UTC, Nirusu commented on .github/docs/conventions.md
> +- the top level directory of the microservice or component, e.g., `joinservice`, `disk-mapper`, `upgrade-agent` but also `docs` and `rfc`
But `devdocs` is technically a violation of this rule :P

2023-01-09 10:14 UTC, derpsteb approved these changes

2023-01-09 10:40 UTC, datosh approved these changes

2023-01-09 10:41 UTC, m1ghtym0 approved these changes

2023-01-09 10:49 UTC, 3u13r approved these changes

2023-01-09 10:51 UTC, merged